version: "3.8"

services:
  app:
    build: .
    container_name: laravel_app
    environment:
      APP_ENV: production
      APP_KEY: base64:GENERATED_KEY
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
    ports:
      - "9000:9000"
    #   - .:/var/www/html
    networks:
      - laravel_net
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  postgres_data:

