version: '3.8'

services:
  # Contenedor de PHP-FPM con Laravel
  app:
    build: .
    container_name: laravel_app
    environment:
      # Variables definidas en tu .env local o .env de docker-compose
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    # IMPORTANTE:
    # Si quieres que el código local sobrescriba el contenedor en desarrollo,
    # descomenta la siguiente línea. Si no, déjalo comentado:
    # volumes:
    #   - .:/var/www/html

    networks:
      - laravel_net
    depends_on:
      - postgres

  # Contenedor Nginx
  web:
    image: nginx:stable
    container_name: laravel_web
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      # Monta el código para que Nginx lo sirva; en dev, te sirve ver cambios en tiempo real
      - .:/var/www/html
      # Montamos la configuración de nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel_net

  # Contenedor PostgreSQL
  postgres:
    image: postgres:15
    container_name: laravel_postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge

volumes:
  postgres_data:
